# Generated by Django 3.2.6 on 2022-09-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Название станка')),
                ('worker', models.CharField(max_length=50, verbose_name='Имя работника')),
                ('published', models.DateField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Станок',
                'verbose_name_plural': 'Станки',
                'ordering': ['-published'],
            },
        ),
    ]
